### ISSUE TITLE
Playcanvas 1.62 breaks the shader

### ISSUE THREAD

**Issue by vogloblinsky** [devcem/easy-shader#1]
Hi,

Thanks for your great Playcanvas shader.

With last version of Playcanvas, 1.62, and their new [Shader chunk system](https://dev-developer.playcanvas.com/en/user-manual/graphics/shader-chunk-migrations/#engine-v162), your shader is broken.

Any chance to have a look ?

Thanks

**Comment by devcem** [comment]
That issue has been fixed, you can get the latest file and use it @vogloblinsky
